### ISSUE TITLE
Can we find and implement a good way to test javascript things?

### ISSUE THREAD

**Issue by elena-vi** [LBHackney-IT/LBH-IncomeCollection#262]
Can we get an acceptance test around this feature?

Is there a good way to test this javascript?

_Originally posted by @kjdchapman in https://github.com/LBHackney-IT/LBH-IncomeCollection/pull/261#issuecomment-565003318_

**Comment by C-gyorfi** [comment]
Can I close this issue? @elena-vi 
added jest in https://github.com/LBHackney-IT/LBH-IncomeCollection/pull/323
